### ISSUE TITLE
Ubuntu version?

### ISSUE THREAD

**Issue by jstefanop** [grmat/opencl-amd#1]
This is awesome...anyway you can whip up a quick version for ubuntu (16.10 that has the 4.8 kernel and open source amdgpu

**Comment by grmat** [comment]
I'm not using Ubuntu currently and neither am I familiar with the packaging there. It's unlikely that I might look into this shortly.

However, the procedure is quite simple:
1. Download and extract the official amdgpu-pro package from AMD
1. acquire libdrm and opencl-related files (`libamdocl64.so`, `libdrm_amdgpu.so.1.0.0`)
1. rename libdrm so you can use it along with the one installed on your distribution
1. modify the opencl file to link to the new, renamed libdrm
1. move the files to the desired location

On the other hand, the OpenCL on ROCm implementation should land soon. You might want to be on the lookout for that.
