### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by mirh** [grmat/opencl-amd#2]
In the order
https://web.archive.org/web/20160609211126/http://www.gearsongallium.com/?p=2960
https://wiki.archlinux.org/index.php/AMDGPU#Enable_Southern_Islands_.28SI.29_and_Sea_Islands_.28CIK.29_support
https://rocm.github.io/

Also please take note, that supposedly ROC is [only](https://www.phoronix.com/scan.php?page=article&item=amd-rocm16-nvidia&num=1) going to be a thing for like Fiji and newer. 
So, at least until clover get opencl 2 compliancy (half a decade?) I don't see this getting deprecated.

**Comment by grmat** [comment]
Thanks, just updated the links.

The deprecation warning still holds, though. They [used to support GPUs older than Fiji](https://github.com/ROCm/ROCm.github.io/blob/5f89a346ee72c442ff845245c58fe264cce5fa71/hardware.html#L59) in the ROCm, although maybe not the newer CL runtime. Experimental support, but keep in mind that SI/CIK support in amdgpu has always been "experimental". I'm not seeing myself maintaining this Frankenstein pkg after OpenCL is available with/on top of mainline packages. If I then still needed to run amdgpu-pro-OpenCL with an older GPU, I'd just run it as a whole -pro stack, maybe even on Ubuntu.

**Comment by mirh** [comment]
Might be frankestein for you cherry picking just some selected file, but it doesn't seem all that of a monstrosity to maintain tbh.

**Comment by grmat** [comment]
Agree, however many users already have problems and I have no hardware to actually test, so I don't see how it makes sense to go on. Anyone is free to take over, of course.

**Comment by znmeb** [comment]
@gmat 
1. I can't get any of the AMDGPU-Pro stack or ROCm to work on Ubuntu 16.04 with my AMD "Bonaire" card. 
2. Clover OpenCL is hopelessly buggy on all distros with my AMD card.

Bottom line: I will never buy another AMD GPU, including the ones Intel will be using in their new chips. The low-level software isn't there, either in open source or proprietary.

**Comment by mirh** [comment]
1. you pinged the wrong dude
2. this repo is by no means affiliated with amd, so I'm not sure who you are yelling at
3. I just linked you the thread for quick info on why ROCm won't ever be the solution to your problem
4. Which doesn't mean this doesn't exist. It's AMDGPU-PRO*. And pretty sure it works on SI too

If it doesn't, it's likely because you need to enable AMDGPU driver from kernel command line. 
But plenty of people reported it works. 

*or fglrx, for all it still matters

EDIT: [bridgman](https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/994473-amd-begins-posting-more-kfd-patches-for-discrete-gpus#post994489) clarifies why ROCm is so 'specific'
EDIT2: [also](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/911118-radeon-open-compute-1-3-platform-brings-polaris-other-features/page9)
EDIT3: [clarification](https://media.readthedocs.org/pdf/rocm-documentation/latest/rocm-documentation.pdf#page=15) on GFX7

**Comment by mirh** [comment]
So.. After some guess work with the latest aforementioned links and [this](https://www.phoronix.com/scan.php?page=news_item&px=Vega-Mainline-Compute-State), I think it can be safely stated that ALL 3rd generation ~~cards~~ gpus are supported by ROCm. 

In addition to that, Hawaii and Kaveri should also going to be tentatively supported (albeit with [limitations](https://www.phoronix.com/forums/forum/software/programming-compilers/926811-gcc-7-0-lands-the-brig-frontend-for-amd-s-hsa#post926938)). 
Unsure about about other [GFX7](https://www.x.org/wiki/RadeonFeature/#index6h2)/2nd Gen hardware (such as the low-end APUs with Sea Islands, or bonaire).. but by then I guess like whatever advantage ROCm might have entailed would be null. 

EDIT: might [nonetheless](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/open-source-amd-linux/867677-setting-up-the-radeon-open-compute-platform-on-linux#post867815) be possible, who knows.
